import 'dart:convert';
import 'dart:io';

/// Puts a compiled runtime inside the Dart package that ships it.
///
/// The TypeScript in a package's `js/` is the source; what a game's script
/// actually loads is the JavaScript it compiles to. Embedding that as a string
/// rather than as an asset means the package works wherever Dart does — a
/// test, a console front end, a build with no asset bundle — and means *using*
/// it needs no node toolchain at all. Only changing it does.
///
/// Every runtime is wrapped and registered the same way, so what differs
/// between them is an entry in [_runtimes] rather than a copy of this file.
void main(List<String> arguments) {
  final name = arguments.length == 1 ? arguments.single : '';
  final runtime = _runtimes[name];
  if (runtime == null) {
    stderr.writeln(
      'Usage: dart tool/embed_runtime.dart <${_runtimes.keys.join('|')}>, '
      'from the repository root.',
    );
    exit(2);
  }

  final built = Directory('${runtime.package}/build/js');
  final sources = {
    for (final module in runtime.sources)
      module: File('${built.path}/$module.js'),
  };

  if (sources.values.any((file) => !file.existsSync())) {
    stderr.writeln(
      'Nothing compiled in ${built.path}. Run `npm run build:$name` from the '
      'repository root first — that is what compiles the TypeScript this '
      'embeds.',
    );
    exit(1);
  }

  final wrapped = _wrap(sources, runtime);
  final quoted = runtime.modules.map((module) => "'$module'").join(', ');

  File('${runtime.package}/lib/src/runtime.g.dart').writeAsStringSync('''
// Generated by tool/embed_runtime.dart from js/. Do not edit.
//
// Checked in on purpose: this is what ships, not a build artefact. A game
// using this package should not need a TypeScript compiler in order to run,
// only in order to write.
//
// To change it: `npm run build:$name` at the repository root.

${_doc(runtime.summary)}
///
${_doc('${runtime.holds} — and a small module registry, so that a file '
      'compiled straight from TypeScript runs without being bundled first.')}
class ${runtime.className} {
  const ${runtime.className}._();

  /// How much JavaScript this is, so a host can budget for it.
  static const int length = ${wrapped.length};

  /// What the library answers `require` for. Anything else has to be bundled
  /// into the script before it is run.
  static const List<String> modules = [$quoted];

  static const String source = ${_dartString(wrapped)};
}
''');

  stdout.writeln('Embedded ${wrapped.length} characters of JavaScript.');
}

/// One embeddable runtime: what goes into it, and what the package that ships
/// it calls the result.
class _Runtime {
  const _Runtime({
    required this.package,
    required this.sources,
    required this.className,
    required this.summary,
    required this.holds,
    required this.modules,
    this.aliases = const {},
  });

  /// Where the package lives, from the repository root.
  final String package;

  /// The compiled files to embed, under the names a script asks for them by.
  /// Each is `<name>.js` in the package's build directory.
  final List<String> sources;

  /// What the generated class is called.
  final String className;

  /// The first line of that class's documentation.
  final String summary;

  /// The rest of it: what loading this runtime puts within a script's reach.
  /// A clause, not a sentence — the module registry is added to it.
  final String holds;

  /// What the library answers `require` for, as the class reports it.
  final List<String> modules;

  /// Further names a module goes by, against the file that defines it.
  final Map<String, String> aliases;
}

const _runtimes = <String, _Runtime>{
  'ui': _Runtime(
    package: 'packages/orblit_script_ui',
    sources: ['ui', 'jsx-runtime'],
    className: 'UiRuntime',
    summary: 'The interface runtime, as the script engine takes it.',
    holds: 'Load this into a script host before any interface script. It '
        'defines the elements, both JSX factories, and the `__orblit_ui` '
        'object the host renders and dispatches through',
    modules: ['orblit', 'orblit/jsx-runtime'],
    aliases: {'orblit': 'ui'},
  ),
  'scene': _Runtime(
    package: 'packages/orblit_script_scene',
    sources: ['scene'],
    className: 'SceneRuntime',
    summary: 'The scene runtime, as the script engine takes it.',
    holds: 'Load this into a script host before any scene script. It defines '
        'what a thing in the world is, the calls that put one there and take '
        'it away again, and the `__orblit_scene` object the host asks each '
        'frame for a description',
    modules: ['orblit/scene'],
  ),
};

/// Wraps the compiled files so the engine can evaluate them as one script.
///
/// TypeScript emits `require` calls and the engine has no idea what a module
/// is. A bundler is the real answer for anything large — that is what every
/// engine of this shape does — but a single file asking for the library it was
/// written against should not need one, so the library registers itself and
/// answers by the last part of whatever path it is asked for.
String _wrap(Map<String, File> sources, _Runtime runtime) {
  final defined = sources.entries
      .map(
        (entry) => 'define(${jsonEncode(entry.key)}, '
            'function (module, exports, require) {\n'
            '${entry.value.readAsStringSync()}\n});',
      )
      .join('\n');

  // Carries its own blank line, so a runtime that renames nothing leaves no
  // gap behind.
  final aliased = runtime.aliases.isEmpty
      ? ''
      : '${runtime.aliases.entries.map(_alias).join()}\n';

  return '''
(function () {
  var modules = {};

  function define(name, factory) {
    var module = { exports: {} };
    factory(module, module.exports, ask);
    modules[name] = module.exports;
  }

  // By the last part of the path, so that "orblit/jsx-runtime",
  // "./jsx-runtime" and "../../js/jsx-runtime" all mean the one thing they
  // can mean here.
  function ask(id) {
    var name = String(id).split('/').pop().replace(/\\.js\$/, '');
    var shared = globalThis.__orblit_modules || {};
    if (Object.prototype.hasOwnProperty.call(modules, name)) {
      return modules[name];
    }
    if (Object.prototype.hasOwnProperty.call(shared, name)) {
      return shared[name];
    }
    throw new Error(
      "Orblit has nothing called '" + id + "'. It knows " +
        Object.keys(modules).join(', ') +
        ". Anything else has to be bundled into the script before it runs."
    );
  }

  if (typeof globalThis.require !== 'function') globalThis.require = ask;

$defined

$aliased  // So a host can register a game's own file under a name and then
  // reach what it exported, and so that two runtimes loaded together share
  // one registry rather than replacing each other's.
  globalThis.__orblit_modules =
      Object.assign(globalThis.__orblit_modules || {}, modules);
})();''';
}

/// One module put within reach under a second name.
String _alias(MapEntry<String, String> alias) {
  final why = _wrapped(
    'The public name of the library, which is what a game writes. The file '
    'it lives in is called ${alias.value}, and that is the '
    "library's business rather than anybody else's.",
    '  // ',
  );
  return "$why\n  modules['${alias.key}'] = modules['${alias.value}'];\n";
}

/// [text] as a documentation comment.
String _doc(String text) => _wrapped(text, '/// ');

/// [text] broken to the width the rest of the repository is written to, with
/// [prefix] beginning every line of it.
String _wrapped(String text, String prefix) {
  final lines = <String>[];
  var line = '';
  for (final word in text.split(' ')) {
    if (line.isEmpty) {
      line = word;
    } else if ('$prefix$line $word'.length <= 80) {
      line = '$line $word';
    } else {
      lines.add('$prefix$line');
      line = word;
    }
  }
  return [...lines, '$prefix$line'].join('\n');
}

/// The string as Dart source.
///
/// Quoted rather than raw, because the JavaScript contains both kinds of
/// quote. JSON encoding handles those and the backslashes, but not the dollar
/// signs — and the JavaScript is full of them, in its own template literals.
/// Dart would read every one as an interpolation, which is a compile error at
/// best and somebody else's variable at worst.
String _dartString(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');
